/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary": "#003824",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#ffddb8",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "outline-variant": "#3c4a42",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "background": "#131313",
        "secondary": "#adc6ff",
        "inverse-primary": "#006c49",
        "surface": "#131313",
        "on-secondary-container": "#e6ecff",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#00422b",
        "surface-bright": "#3a3939",
        "tertiary-container": "#e29100",
        "primary": "#4edea3",
        "on-tertiary-container": "#523200",
        "on-primary-fixed-variant": "#005236",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353534",
        "on-secondary": "#002e6a",
        "on-surface-variant": "#bbcabf",
        "outline": "#86948a",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#4edea3",
        "secondary-container": "#0566d9",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#2a1700",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#001a42",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#002113",
        "primary-container": "#10b981"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "max-width-desktop": "1440px",
        "section-gap": "48px",
        "container-padding": "24px",
        "base": "8px",
        "gutter": "20px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "display-hero": ["Inter"],
        "display-hero-mobile": ["Inter"],
        "label-caps": ["Geist"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "data-mono": ["Geist"],
        "body-md": ["Inter"]
      }
    },
  },
  plugins: [],
}
